# Generated by Django 3.1.7 on 2021-02-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pro_descripcion',
            field=models.TextField(null=True),
        ),
    ]
