# Generated by Django 3.1.7 on 2021-02-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0005_auto_20210222_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pro_imagen',
            field=models.ImageField(default='default.png', max_length=128, upload_to='PRODUCTOS'),
        ),
    ]
